# Generated by Django 4.0.5 on 2022-06-10 06:15

import coplate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, error_messages={'validators': '주소에 특수문자는 포함될 수 없습니다.'}, max_length=40, validators=[coplate.validators.validate_no_special_characters]),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, error_messages={'validators': '카카오ID에 특수문자는 포함될 수 없습니다.'}, max_length=20, validators=[coplate.validators.validate_no_special_characters]),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, error_messages={'unique': '이미 사용 중인 닉네임입니다.', 'validators': '닉네임에 특수문자는 포함될 수 없습니다.'}, max_length=15, unique=True, validators=[coplate.validators.validate_no_special_characters]),
        ),
    ]
